[book]
title = "Copia CLI Manual"
authors = ["Qubernetic"]
language = "en"
src = "src"

[build]
build-dir = "../../site"

[output.html]
git-repository-url = "https://github.com/qubernetic-org/copia-cli"
edit-url-template = "https://github.com/qubernetic-org/copia-cli/edit/develop/docs/manual/{path}"
